services:
  web:
    build: .
    container_name: markaz-backend
    restart: always
    ports:
      - "8002:8002"
    volumes:
      - db_data:/app/data
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings_prod

volumes:
  db_data:
