services:
  web:
    build: .
    container_name: markaz-backend
    restart: always
    ports:
      - "8002:8002"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./media:/app/media
      - static_files:/app/staticfiles
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings_prod

volumes:
  static_files:
