# Generated by Django 6.0.3 on 2026-03-30 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug (ID)')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('population', models.PositiveIntegerField(default=0, verbose_name='Aholi soni')),
            ],
            options={
                'verbose_name': 'Tuman',
                'verbose_name_plural': 'Tumanlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug (ID)')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('population', models.PositiveIntegerField(default=0, verbose_name='Aholi soni')),
                ('center_lat', models.FloatField(default=0, verbose_name='Markaz (kenglik)')),
                ('center_lng', models.FloatField(default=0, verbose_name='Markaz (uzunlik)')),
            ],
            options={
                'verbose_name': 'Viloyat',
                'verbose_name_plural': 'Viloyatlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CulturalCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('category', models.CharField(choices=[('vazirlik', 'Vazirlik'), ('hokimlik', 'Hokimlik'), ('dxsh', 'DXSh'), ('sotiladi', 'Sotiladi')], max_length=20, verbose_name='Kategoriya')),
                ('lat', models.FloatField(verbose_name='Kenglik (latitude)')),
                ('lng', models.FloatField(verbose_name='Uzunlik (longitude)')),
                ('address', models.CharField(max_length=500, verbose_name='Manzil')),
                ('director', models.CharField(blank=True, max_length=200, verbose_name='Rahbar')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('employees', models.PositiveIntegerField(default=0, verbose_name='Xodimlar soni')),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name="Sig'imi")),
                ('built_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Qurilgan yili')),
                ('condition', models.CharField(choices=[('Yaxshi', 'Yaxshi'), ("O'rtacha", "O'rtacha"), ('Yomon', 'Yomon'), ('Tamir talab', 'Tamir talab')], default='Yaxshi', max_length=20, verbose_name='Holati')),
                ('area_sqm', models.PositiveIntegerField(default=0, verbose_name='Maydoni (kv.m)')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('image', models.ImageField(blank=True, null=True, upload_to='centers/', verbose_name='Rasm')),
                ('mahalla_id', models.CharField(blank=True, max_length=20, verbose_name='Mahalla ID (SOATO)')),
                ('mahalla_name', models.CharField(blank=True, max_length=100, verbose_name='Mahalla nomi')),
                ('mahalla_population', models.PositiveIntegerField(default=0, verbose_name='Mahalla aholisi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centers', to='centers.district', verbose_name='Tuman')),
            ],
            options={
                'verbose_name': 'Madaniyat markazi',
                'verbose_name_plural': 'Madaniyat markazlari',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='centers.region', verbose_name='Viloyat'),
        ),
    ]
