# Generated by Django 6.0.3 on 2026-03-30 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culturalcenter',
            name='mahalla_id',
        ),
        migrations.RemoveField(
            model_name='culturalcenter',
            name='mahalla_name',
        ),
        migrations.RemoveField(
            model_name='culturalcenter',
            name='mahalla_population',
        ),
        migrations.AddField(
            model_name='district',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nomi (ruscha)'),
        ),
        migrations.AddField(
            model_name='district',
            name='soato',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='SOATO kodi'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nomi (ruscha)'),
        ),
        migrations.AddField(
            model_name='region',
            name='soato',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='SOATO kodi'),
        ),
        migrations.CreateModel(
            name='Mahalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('tin', models.CharField(max_length=20, unique=True, verbose_name='INN (TIN)')),
                ('soato', models.CharField(blank=True, max_length=15, verbose_name='SOATO kodi')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Kod')),
                ('name_uz', models.CharField(blank=True, max_length=200, verbose_name='Nomi (kirill)')),
                ('name_ru', models.CharField(blank=True, max_length=200, verbose_name='Nomi (ruscha)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Nomi (inglizcha)')),
                ('population', models.PositiveIntegerField(default=0, verbose_name='Aholi soni')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahallas', to='centers.district', verbose_name='Tuman')),
            ],
            options={
                'verbose_name': 'Mahalla',
                'verbose_name_plural': 'Mahallalar',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='culturalcenter',
            name='mahalla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centers', to='centers.mahalla', verbose_name='Mahalla'),
        ),
    ]
