# Generated by Django 6.0.3 on 2026-03-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_remove_culturalcenter_mahalla_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='soato',
            field=models.CharField(blank=True, db_index=True, max_length=10, verbose_name='SOATO kodi'),
        ),
        migrations.AlterField(
            model_name='region',
            name='soato',
            field=models.CharField(blank=True, db_index=True, max_length=10, verbose_name='SOATO kodi'),
        ),
    ]
