# Generated by Django 6.0.1 on 2026-03-31 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0003_alter_district_soato_alter_region_soato'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturalcenter',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nomi (inglizcha)'),
        ),
        migrations.AddField(
            model_name='culturalcenter',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nomi (ruscha)'),
        ),
        migrations.AddField(
            model_name='district',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nomi (inglizcha)'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nomi (inglizcha)'),
        ),
    ]
