# Generated by Django 6.0.1 on 2026-03-31 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0004_culturalcenter_name_en_culturalcenter_name_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalCenterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='centers/gallery/', verbose_name='Rasm')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='centers.culturalcenter', verbose_name='Markaz')),
            ],
            options={
                'verbose_name': 'Rasm',
                'verbose_name_plural': 'Rasmlar',
                'ordering': ['order'],
            },
        ),
    ]
