# Generated by Django 6.0.1 on 2026-03-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0005_culturalcenterimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Faoliyat turi',
                'verbose_name_plural': 'Faoliyat turlari',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='culturalcenter',
            name='area_sqm',
        ),
        migrations.RemoveField(
            model_name='culturalcenter',
            name='employees',
        ),
        migrations.AddField(
            model_name='culturalcenter',
            name='additional_buildings_count',
            field=models.PositiveIntegerField(default=0, verbose_name="Qo'shimcha binolar soni"),
        ),
        migrations.AddField(
            model_name='culturalcenter',
            name='auditorium_area',
            field=models.FloatField(default=0, verbose_name='Tomosha zali maydoni (kv.m)'),
        ),
        migrations.AddField(
            model_name='culturalcenter',
            name='balance_holder',
            field=models.CharField(blank=True, max_length=500, verbose_name='Balansda saqlovchi'),
        ),
        migrations.AddField(
            model_name='culturalcenter',
            name='building_area',
            field=models.FloatField(default=0, verbose_name='Bino va inshoatlar maydoni (kv.m)'),
        ),
        migrations.AddField(
            model_name='culturalcenter',
            name='building_floors',
            field=models.PositiveIntegerField(default=0, verbose_name='Bino qavati'),
        ),
        migrations.AddField(
            model_name='culturalcenter',
            name='building_technical_info',
            field=models.TextField(blank=True, verbose_name='Binoning texnik xarakteristikasi'),
        ),
        migrations.AddField(
            model_name='culturalcenter',
            name='buildings_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Mavjud binolar soni'),
        ),
        migrations.AddField(
            model_name='culturalcenter',
            name='circles_count',
            field=models.PositiveIntegerField(default=0, verbose_name="To'garaklar soni"),
        ),
        migrations.AddField(
            model_name='culturalcenter',
            name='creative_staff',
            field=models.PositiveIntegerField(default=0, verbose_name='Ijodiy xadimlar soni'),
        ),
        migrations.AddField(
            model_name='culturalcenter',
            name='dining_area',
            field=models.FloatField(default=0, verbose_name='Ovqatlanish maydoni (kv.m)'),
        ),
        migrations.AddField(
            model_name='culturalcenter',
            name='library_activity_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Kutubxona faoliyat soni'),
        ),
        migrations.AddField(
            model_name='culturalcenter',
            name='management_staff',
            field=models.FloatField(default=0, verbose_name='Boshqaruv shtat birligi'),
        ),
        migrations.AddField(
            model_name='culturalcenter',
            name='restrooms_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Xojatxonalar soni'),
        ),
        migrations.AddField(
            model_name='culturalcenter',
            name='rooms_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Xonalar soni'),
        ),
        migrations.AddField(
            model_name='culturalcenter',
            name='technical_staff',
            field=models.PositiveIntegerField(default=0, verbose_name='Texnik xodimlar soni'),
        ),
        migrations.AddField(
            model_name='culturalcenter',
            name='titled_team_staff',
            field=models.PositiveIntegerField(default=0, verbose_name='Unvonga ega jamoalar xodimlari soni'),
        ),
        migrations.AddField(
            model_name='culturalcenter',
            name='titled_teams_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Unvonga ega jamoalar soni'),
        ),
        migrations.AddField(
            model_name='culturalcenter',
            name='total_land_area',
            field=models.FloatField(default=0, verbose_name='Umumiy yer maydoni (ga)'),
        ),
        migrations.AlterField(
            model_name='culturalcenter',
            name='built_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Binolar qurilgan yil'),
        ),
        migrations.AlterField(
            model_name='culturalcenter',
            name='condition',
            field=models.CharField(choices=[('Yaxshi', 'Yaxshi'), ("O'rtacha", "O'rtacha"), ('Yomon', 'Yomon'), ('Tamir talab', 'Tamir talab')], default='Yaxshi', max_length=20, verbose_name='Bino holati'),
        ),
        migrations.AddField(
            model_name='culturalcenter',
            name='activity_types',
            field=models.ManyToManyField(blank=True, related_name='centers', to='centers.activitytype', verbose_name='Faoliyat turlari'),
        ),
    ]
