# Generated by Django 6.0.1 on 2026-03-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0006_activitytype_remove_culturalcenter_area_sqm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturalcenter',
            name='has_electricity',
            field=models.BooleanField(default=False, verbose_name='Elektro-energiya'),
        ),
        migrations.AddField(
            model_name='culturalcenter',
            name='has_gas',
            field=models.BooleanField(default=False, verbose_name='Gaz'),
        ),
        migrations.AddField(
            model_name='culturalcenter',
            name='has_heating',
            field=models.BooleanField(default=False, verbose_name='Isitish tizimi'),
        ),
        migrations.AddField(
            model_name='culturalcenter',
            name='has_sewerage',
            field=models.BooleanField(default=False, verbose_name='Kanalizatsiya'),
        ),
        migrations.AddField(
            model_name='culturalcenter',
            name='has_water',
            field=models.BooleanField(default=False, verbose_name='Ichimlik suvi'),
        ),
    ]
