# Generated by Django 6.0.1 on 2026-03-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0007_culturalcenter_has_electricity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturalcenter',
            name='map_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Xarita havolasi (Google/Yandex)'),
        ),
    ]
