# Generated by Django 6.0.1 on 2026-03-31 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0008_culturalcenter_map_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culturalcenter',
            name='description',
        ),
        migrations.RemoveField(
            model_name='culturalcenter',
            name='director',
        ),
        migrations.RemoveField(
            model_name='culturalcenter',
            name='phone',
        ),
    ]
