# Generated by Django 6.0.1 on 2026-03-31 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0009_remove_culturalcenter_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culturalcenter',
            name='capacity',
        ),
    ]
