# Generated by Django 6.0.1 on 2026-03-31 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0010_remove_culturalcenter_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturalcenter',
            name='serving_mahallas',
            field=models.ManyToManyField(blank=True, related_name='served_by_centers', to='centers.mahalla', verbose_name='Xizmat qiluvchi mahallalar'),
        ),
    ]
