# Generated by Django 6.0.1 on 2026-03-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0011_culturalcenter_serving_mahallas'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturalcenter',
            name='has_own_building',
            field=models.BooleanField(default=True, verbose_name="O'z binosiga ega"),
        ),
    ]
