# Generated by Django 6.0.1 on 2026-04-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0012_culturalcenter_has_own_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturalcenter',
            name='category',
            field=models.CharField(choices=[('vazirlik', 'Vazirlik'), ('hokimlik', 'Hokimlik'), ('dxsh', 'DXSh'), ('tugatiladi', 'Tugatiladi')], max_length=20, verbose_name='Kategoriya'),
        ),
    ]
