# Generated by Django 6.0.1 on 2026-04-01 06:13

from django.db import migrations


def rename_category(apps, schema_editor):
    CulturalCenter = apps.get_model('centers', 'CulturalCenter')
    CulturalCenter.objects.filter(category='sotiladi').update(category='tugatiladi')


def reverse_rename(apps, schema_editor):
    CulturalCenter = apps.get_model('centers', 'CulturalCenter')
    CulturalCenter.objects.filter(category='tugatiladi').update(category='sotiladi')


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0013_alter_culturalcenter_category'),
    ]

    operations = [
        migrations.RunPython(rename_category, reverse_rename),
    ]
