# Generated by Django 6.0.1 on 2026-04-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0014_rename_sotiladi_to_tugatiladi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culturalcenter',
            name='address',
        ),
        migrations.AddField(
            model_name='culturalcenter',
            name='balance_holder_ru',
            field=models.CharField(blank=True, max_length=500, verbose_name='Balansda saqlovchi (ruscha)'),
        ),
        migrations.AddField(
            model_name='culturalcenter',
            name='building_technical_info_ru',
            field=models.TextField(blank=True, verbose_name='Binoning texnik xarakteristikasi (ruscha)'),
        ),
    ]
