# Generated by Django 6.0.1 on 2026-04-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0015_remove_culturalcenter_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culturalcenter',
            name='auditorium_area',
        ),
        migrations.AddField(
            model_name='culturalcenter',
            name='auditorium_seats',
            field=models.PositiveIntegerField(default=0, verbose_name="Tomosha zali (o’rin)"),
        ),
    ]
