# Generated by Django 6.0.1 on 2026-04-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0016_remove_culturalcenter_auditorium_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturalcenter',
            name='condition',
            field=models.CharField(choices=[('Yaxshi', 'Yaxshi'), ("O'rtacha", "O'rtacha"), ('Avariya holatida', 'Avariya holatida'), ('Tamir talab', 'Tamir talab')], default='Yaxshi', max_length=20, verbose_name='Bino holati'),
        ),
    ]
