# Generated by Django 6.0.1 on 2026-04-01 11:46

from django.db import migrations


def rename_condition(apps, schema_editor):
    CulturalCenter = apps.get_model('centers', 'CulturalCenter')
    CulturalCenter.objects.filter(condition='Yomon').update(condition='Avariya holatida')


def reverse_rename(apps, schema_editor):
    CulturalCenter = apps.get_model('centers', 'CulturalCenter')
    CulturalCenter.objects.filter(condition='Avariya holatida').update(condition='Yomon')


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0017_alter_culturalcenter_condition'),
    ]

    operations = [
        migrations.RunPython(rename_condition, reverse_rename),
    ]
