# Generated by Django 6.0.1 on 2026-04-01 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0018_rename_yomon_to_avariya'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culturalcenter',
            name='map_url',
        ),
        migrations.AlterField(
            model_name='culturalcenter',
            name='mahalla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centers', to='centers.mahalla', verbose_name='Mahalla'),
        ),
    ]
