# Generated by Django 6.0.1 on 2026-04-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0019_remove_map_url_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturalcenter',
            name='creative_staff',
            field=models.FloatField(default=0, verbose_name='Ijodiy xadimlar soni'),
        ),
        migrations.AlterField(
            model_name='culturalcenter',
            name='technical_staff',
            field=models.FloatField(default=0, verbose_name='Texnik xodimlar soni'),
        ),
        migrations.AlterField(
            model_name='culturalcenter',
            name='titled_team_staff',
            field=models.FloatField(default=0, verbose_name='Unvonga ega jamoalar xodimlari soni'),
        ),
    ]
