# Generated by Django 6.0.1 on 2026-04-07 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0020_alter_culturalcenter_creative_staff_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit_basic', models.BooleanField(default=True, verbose_name="Asosiy ma'lumotlar")),
                ('can_edit_location', models.BooleanField(default=False, verbose_name='Joylashuv')),
                ('can_edit_about', models.BooleanField(default=False, verbose_name="Obyekt haqida ma'lumot")),
                ('can_edit_staff', models.BooleanField(default=True, verbose_name='xadimlar')),
                ('can_edit_classification', models.BooleanField(default=False, verbose_name='Obyekt tasnifi')),
                ('can_edit_utilities', models.BooleanField(default=False, verbose_name='Kommunikatsiyalar')),
                ('region', models.ForeignKey(blank=True, help_text="Faqat shu viloyatdagi markazlarni ko'radi. Bo'sh = barcha viloyatlar", null=True, on_delete=django.db.models.deletion.SET_NULL, to='centers.region', verbose_name='Viloyat')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Admin profil',
                'verbose_name_plural': 'Admin profillar',
            },
        ),
    ]
