# Generated by Django 6.0.1 on 2026-04-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0021_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='can_edit_images',
            field=models.BooleanField(default=False, verbose_name='Rasmlar'),
        ),
    ]
