# Generated by Django 6.0.1 on 2026-04-07 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0022_adminprofile_can_edit_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culturalcenter',
            name='image',
        ),
    ]
