# Generated by Django 6.0.1 on 2026-04-07 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0023_remove_culturalcenter_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='can_edit_featured',
            field=models.BooleanField(default=False, verbose_name='Ajratilgan markaz'),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='can_edit_projects',
            field=models.BooleanField(default=False, verbose_name='Loyihalar'),
        ),
        migrations.AddField(
            model_name='culturalcenter',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Ajratilgan markaz'),
        ),
        migrations.CreateModel(
            name='CulturalCenterProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('media_type', models.CharField(choices=[('image', 'Rasm'), ('video', 'Video')], default='image', max_length=10, verbose_name='Turi')),
                ('file', models.FileField(upload_to='centers/projects/', verbose_name='Fayl (rasm yoki video)')),
                ('caption', models.CharField(blank=True, max_length=500, verbose_name='Izoh')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='centers.culturalcenter', verbose_name='Markaz')),
            ],
            options={
                'verbose_name': 'Loyiha',
                'verbose_name_plural': 'Loyihalar',
                'ordering': ['order'],
            },
        ),
    ]
