# Generated by Django 6.0.1 on 2026-04-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0024_adminprofile_can_edit_featured_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='can_edit_about',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='can_edit_basic',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='can_edit_classification',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='can_edit_featured',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='can_edit_location',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='can_edit_staff',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='can_edit_utilities',
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='allowed_fields',
            field=models.JSONField(blank=True, default=list, help_text="Tanlangan maydonlarni admin tahrirlashi mumkin. Tanlanmaganlar faqat o'qish uchun.", verbose_name="Tahrirlash mumkin bo'lgan maydonlar"),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='can_edit_images',
            field=models.BooleanField(default=False, verbose_name="Rasmlar qo'shish/tahrirlash"),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='can_edit_projects',
            field=models.BooleanField(default=False, verbose_name="Loyihalar qo'shish/tahrirlash"),
        ),
    ]
