# Generated by Django 6.0.1 on 2026-04-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0025_remove_adminprofile_can_edit_about_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('button_label', models.CharField(max_length=100, verbose_name='Tugma matni')),
                ('image', models.ImageField(upload_to='slides/', verbose_name='Rasm (JPG)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Sliderlar',
                'ordering': ['order'],
            },
        ),
    ]
