# Generated by Django 6.0.1 on 2026-04-11 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0026_slide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='image',
        ),
        migrations.CreateModel(
            name='SlideImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slides/images/', verbose_name='Rasm')),
                ('video', models.FileField(blank=True, help_text="Rasmga bog'langan video fayl (ixtiyoriy)", upload_to='slides/videos/', verbose_name='Video')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='centers.slide', verbose_name='Slide')),
            ],
            options={
                'verbose_name': 'Slide rasmi',
                'verbose_name_plural': 'Slide rasmlari',
                'ordering': ['order'],
            },
        ),
    ]
