# Generated by Django 6.0.1 on 2026-04-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0027_remove_slide_image_slideimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='button_label_en',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Tugma matni (en)'),
        ),
        migrations.AddField(
            model_name='slide',
            name='button_label_ru',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Tugma matni (ru)'),
        ),
        migrations.AddField(
            model_name='slide',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nomi (en)'),
        ),
        migrations.AddField(
            model_name='slide',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nomi (ru)'),
        ),
        migrations.AddField(
            model_name='slideimage',
            name='caption_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Izoh (en)'),
        ),
        migrations.AddField(
            model_name='slideimage',
            name='caption_ru',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Izoh (ru)'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='button_label',
            field=models.CharField(max_length=100, verbose_name='Tugma matni (uz)'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Nomi (uz)'),
        ),
        migrations.AlterField(
            model_name='slideimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255, verbose_name='Izoh (uz)'),
        ),
    ]
