# Generated by Django 6.0.1 on 2026-04-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0028_slide_multilang_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='button_label_en',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='slideimage',
            name='caption_en',
        ),
        migrations.AddField(
            model_name='slide',
            name='button_label_uz',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Tugma matni (kirill)'),
        ),
        migrations.AddField(
            model_name='slide',
            name='title_uz',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nomi (kirill)'),
        ),
        migrations.AddField(
            model_name='slideimage',
            name='caption_uz',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Izoh (kirill)'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='button_label',
            field=models.CharField(max_length=100, verbose_name='Tugma matni (lotin)'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='button_label_ru',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Tugma matni (ruscha)'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Nomi (lotin)'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nomi (ruscha)'),
        ),
        migrations.AlterField(
            model_name='slideimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255, verbose_name='Izoh (lotin)'),
        ),
        migrations.AlterField(
            model_name='slideimage',
            name='caption_ru',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Izoh (ruscha)'),
        ),
    ]
