# Generated by Django 6.0.1 on 2026-04-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0029_slide_fix_langs_uz_cyrl_ru'),
    ]

    operations = [
        # Region, District, CulturalCenter: name_en -> name_uz (ma'lumotni saqlab qolish)
        migrations.RenameField(
            model_name='region',
            old_name='name_en',
            new_name='name_uz',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='name_en',
            new_name='name_uz',
        ),
        migrations.RenameField(
            model_name='culturalcenter',
            old_name='name_en',
            new_name='name_uz',
        ),
        # Mahalla: name_en ni olib tashlash (name_uz allaqachon mavjud)
        migrations.RemoveField(
            model_name='mahalla',
            name='name_en',
        ),
        # verbose_name larni yangilash
        migrations.AlterField(
            model_name='region',
            name='name_uz',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nomi (kirill)'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name_uz',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nomi (kirill)'),
        ),
        migrations.AlterField(
            model_name='culturalcenter',
            name='name_uz',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nomi (kirill)'),
        ),
    ]
