# Generated by Django 6.0.1 on 2026-04-11 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0030_rename_en_to_uz_cyrl'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi (lotin)')),
                ('title_uz', models.CharField(blank=True, default='', max_length=255, verbose_name='Nomi (kirill)')),
                ('title_ru', models.CharField(blank=True, default='', max_length=255, verbose_name='Nomi (ruscha)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Mehmonxona',
                'verbose_name_plural': 'Mehmonxona',
            },
        ),
        migrations.CreateModel(
            name='GuestHouseMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Rasm'), ('video', 'Video')], default='image', max_length=10, verbose_name='Turi')),
                ('image', models.ImageField(blank=True, upload_to='guesthouse/images/', verbose_name='Rasm')),
                ('video', models.FileField(blank=True, upload_to='guesthouse/videos/', verbose_name='Video')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Izoh (lotin)')),
                ('caption_uz', models.CharField(blank=True, default='', max_length=255, verbose_name='Izoh (kirill)')),
                ('caption_ru', models.CharField(blank=True, default='', max_length=255, verbose_name='Izoh (ruscha)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('guest_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='centers.guesthouse', verbose_name='Mehmonxona')),
            ],
            options={
                'verbose_name': 'Mehmonxona media',
                'verbose_name_plural': 'Mehmonxona media',
                'ordering': ['order'],
            },
        ),
    ]
