# Generated by Django 6.0.3 on 2026-04-15 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0033_center_not_both_featured_and_dxsh'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExemplaryCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi (lotin)')),
                ('title_uz', models.CharField(blank=True, default='', max_length=255, verbose_name='Nomi (kirill)')),
                ('title_ru', models.CharField(blank=True, default='', max_length=255, verbose_name='Nomi (ruscha)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Namunali markaz',
                'verbose_name_plural': 'Namunali markaz',
            },
        ),
        migrations.CreateModel(
            name='ExemplaryCenterMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Rasm'), ('video', 'Video')], default='image', max_length=10, verbose_name='Turi')),
                ('image', models.ImageField(blank=True, upload_to='exemplary/images/', verbose_name='Rasm')),
                ('video', models.FileField(blank=True, upload_to='exemplary/videos/', verbose_name='Video')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Izoh (lotin)')),
                ('caption_uz', models.CharField(blank=True, default='', max_length=255, verbose_name='Izoh (kirill)')),
                ('caption_ru', models.CharField(blank=True, default='', max_length=255, verbose_name='Izoh (ruscha)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Namunali markaz media',
                'verbose_name_plural': 'Namunali markaz media',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='culturalcenter',
            name='center_not_both_featured_and_dxsh',
        ),
        migrations.AddConstraint(
            model_name='culturalcenter',
            constraint=models.CheckConstraint(condition=models.Q(('is_dxsh_project', True), ('is_featured', True), _negated=True), name='center_not_both_featured_and_dxsh'),
        ),
        migrations.AddField(
            model_name='exemplarycentermedia',
            name='exemplary_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='centers.exemplarycenter', verbose_name='Namunali markaz'),
        ),
    ]
